package dayThreeFour.thread_methods;

class CreateThread extends Thread {
    @Override
    public void run() {
        for (int i = 0; i < 5; i++) {
            System.out.println(Thread.currentThread().getName() + " is running..." + i);
            Thread.yield();
        }
    }
}

public class CodeFive {
    public static void main(String[] args) {
        CreateThread t1 = new CreateThread();
        CreateThread t2 = new CreateThread();
        t1.start();
        t2.start();
    }
}

/*
    Output when yield() is not used:
    Thread-0 is running...
    Thread-0 is running...
    Thread-0 is running...
    Thread-0 is running...
    Thread-0 is running...
    Thread-1 is running...
    Thread-1 is running...
    Thread-1 is running...
    Thread-1 is running...
    Thread-1 is running...
*/

/*
    Output when yield() is used:
    Thread-1 is running...
    Thread-1 is running...
    Thread-0 is running...
    Thread-0 is running...
    Thread-0 is running...
    Thread-1 is running...
    Thread-0 is running...
    Thread-0 is running...
    Thread-1 is running...
    Thread-1 is running...
*/
